name: Bunny.Net Deployment CI/CD

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [function_trigger]

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'repository_dispatch'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:cicd
          use-cache: true
      - name: Build
        run: |
          npm ci
          npm run build
      - name: Deploy to BunnyCDN
        uses: ayeressian/bunnycdn-storage-deploy@v2.3.0
        with:
          source: "dist"
          destination: ""
          storageZoneName: "${{ secrets.STORAGE_NAME }}"
          storagePassword: "${{ secrets.STORAGE_PASSWORD }}"
          storageEndpoint: "uk.storage.bunnycdn.com"
          accessKey: "${{ secrets.ACCESS_KEY }}"
          pullZoneId: "${{ secrets.ZONE_ID }}"
          upload: "true"
          remove: "true"
          purgePullZone: "true"
          purgePullZoneDelay: "15"
      - name: send webhook
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{"message": "Deployment to Bunny completed successfully."}' "${{ secrets.WEBHOOK_URL }}"
        env:
          WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}